[package]
name = "grove-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "grove_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
jni = "=0.21.1"
serde_json = "=1.0.145"

num-bigint = "=0.4.6"
num-traits = "=0.2.19"
num-integer = "=0.1.46"
unicode-normalization = "=0.1.24"
