package tech.granet.grove

import android.content.Context

/** Resource-backed labels shared by discovery and the controls with stable IDs. */
internal object SettingsLabels {
    private val resources = mapOf(
        "APPS_BUTTON" to (R.string.settings_search_apps_button to R.string.settings_search_apps_button_path),
        "SEARCH_BUTTON" to (R.string.settings_search_search_button to R.string.settings_search_search_button_path),
        "CLOCK" to (R.string.settings_search_clock to R.string.settings_search_clock_path),
        "CLOCK_ACTION" to (R.string.settings_search_clock_action to R.string.settings_search_clock_action_path),
        "PINS" to (R.string.settings_search_pins to R.string.settings_search_pins_path),
        "PIN_BOTTOM" to (R.string.settings_search_pin_bottom to R.string.settings_search_pin_bottom_path),
        "SWIPE_SEARCH" to (R.string.settings_search_swipe_search to R.string.settings_search_swipe_search_path),
        "SWIPE_DRAWER" to (R.string.settings_search_swipe_drawer to R.string.settings_search_swipe_drawer_path),
        "TAP_MENU" to (R.string.settings_search_tap_menu to R.string.settings_search_tap_menu_path),
        "HOLD_MENU" to (R.string.settings_search_hold_menu to R.string.settings_search_hold_menu_path),
        "WALLPAPER_COLORS" to (R.string.settings_search_wallpaper_colors to R.string.settings_search_wallpaper_colors_path),
        "CALCULATOR" to (R.string.settings_search_calculator to R.string.settings_search_calculator_path),
        "GROVE_SETTINGS" to (R.string.settings_search_grove_settings to R.string.settings_search_grove_settings_path),
        "ANDROID_SETTINGS" to (R.string.settings_search_android_settings to R.string.settings_search_android_settings_path),
        "CONTACTS" to (R.string.settings_search_contacts to R.string.settings_search_contacts_path),
        "FILES" to (R.string.settings_search_files to R.string.settings_search_files_path),
        "CONTACT_INDEX" to (R.string.settings_search_contact_index to R.string.settings_search_contact_index_path),
        "FILE_INDEX" to (R.string.settings_search_file_index to R.string.settings_search_file_index_path),
        "widgets" to (R.string.settings_search_widgets to R.string.settings_search_widgets_path),
        "homeGrid" to (R.string.settings_search_homegrid to R.string.settings_search_homegrid_path),
        "drawerGrid" to (R.string.settings_search_drawergrid to R.string.settings_search_drawergrid_path),
        "folders" to (R.string.settings_search_folders to R.string.settings_search_folders_path),
        "launcher" to (R.string.settings_search_launcher to R.string.settings_search_launcher_path),
        "theme" to (R.string.settings_search_theme to R.string.settings_search_theme_path),
        "wallpaper" to (R.string.settings_search_wallpaper to R.string.settings_search_wallpaper_path),
        "import" to (R.string.settings_search_import to R.string.settings_search_import_path),
        "export" to (R.string.settings_search_export to R.string.settings_search_export_path),
        "editor" to (R.string.settings_search_editor to R.string.settings_search_editor_path),
        "recovery" to (R.string.settings_search_recovery to R.string.settings_search_recovery_path),
        "defaults" to (R.string.settings_search_defaults to R.string.settings_search_defaults_path),
        "tutorial" to (R.string.settings_search_tutorial to R.string.settings_search_tutorial_path),
        "searchTutorial" to (R.string.search_tutorial_replay to R.string.settings_search_tutorial_path),
        "capture" to (R.string.settings_search_capture to R.string.settings_search_capture_path),
        "email" to (R.string.settings_search_email to R.string.settings_search_email_path),
        "reports" to (R.string.settings_search_reports to R.string.settings_search_reports_path),
        "deleteReports" to (R.string.settings_search_deletereports to R.string.settings_search_deletereports_path),
        "project" to (R.string.settings_search_project to R.string.settings_search_project_path),
        "privacy" to (R.string.settings_search_privacy to R.string.settings_search_privacy_path),
        "licenses" to (R.string.settings_search_licenses to R.string.settings_search_licenses_path),
        "credits" to (R.string.settings_search_credits to R.string.settings_search_credits_path),
        "category-root" to (R.string.settings_search_category_root to R.string.settings_search_category_root_path),
        "category-home" to (R.string.settings_search_category_home to R.string.settings_search_category_home_path),
        "category-drawer" to (R.string.settings_search_category_drawer to R.string.settings_search_category_drawer_path),
        "category-search" to (R.string.settings_search_category_search to R.string.settings_search_category_search_path),
        "category-appearance" to (R.string.settings_search_category_appearance to R.string.settings_search_category_appearance_path),
        "category-configuration" to (R.string.settings_search_category_configuration to R.string.settings_search_category_configuration_path),
        "category-help" to (R.string.settings_search_category_help to R.string.settings_search_category_help_path),
        "category-about" to (R.string.settings_search_category_about to R.string.settings_search_category_about_path),
        "access-contacts" to (R.string.settings_search_access_contacts to R.string.settings_search_access_contacts_path),
        "access-files" to (R.string.settings_search_access_files to R.string.settings_search_access_files_path),
        "refresh-contacts" to (R.string.settings_search_refresh_contacts to R.string.settings_search_refresh_contacts_path),
        "refresh-files" to (R.string.settings_search_refresh_files to R.string.settings_search_refresh_files_path),
        "android-wifi" to (R.string.settings_search_android_wifi to R.string.settings_search_android_wifi_path),
        "android-bluetooth" to (R.string.settings_search_android_bluetooth to R.string.settings_search_android_bluetooth_path),
        "android-airplane" to (R.string.settings_search_android_airplane to R.string.settings_search_android_airplane_path),
        "android-wireless" to (R.string.settings_search_android_wireless to R.string.settings_search_android_wireless_path),
        "android-display" to (R.string.settings_search_android_display to R.string.settings_search_android_display_path),
        "android-sound" to (R.string.settings_search_android_sound to R.string.settings_search_android_sound_path),
        "android-notifications" to (R.string.settings_search_android_notifications to R.string.settings_search_android_notifications_path),
        "android-apps" to (R.string.settings_search_android_apps to R.string.settings_search_android_apps_path),
        "android-storage" to (R.string.settings_search_android_storage to R.string.settings_search_android_storage_path),
        "android-battery" to (R.string.settings_search_android_battery to R.string.settings_search_android_battery_path),
        "android-security" to (R.string.settings_search_android_security to R.string.settings_search_android_security_path),
        "android-privacy" to (R.string.settings_search_android_privacy to R.string.settings_search_android_privacy_path),
        "android-accessibility" to (R.string.settings_search_android_accessibility to R.string.settings_search_android_accessibility_path),
        "android-location" to (R.string.settings_search_android_location to R.string.settings_search_android_location_path),
        "android-language" to (R.string.settings_search_android_language to R.string.settings_search_android_language_path),
        "android-date" to (R.string.settings_search_android_date to R.string.settings_search_android_date_path),
        "android-vpn" to (R.string.settings_search_android_vpn to R.string.settings_search_android_vpn_path),
        "android-defaultApps" to (R.string.settings_search_android_defaultapps to R.string.settings_search_android_defaultapps_path),
        "android-home" to (R.string.settings_search_android_home to R.string.settings_search_android_home_path),
        "android-search" to (R.string.settings_search_android_search to R.string.settings_search_android_search_path),
        "android-root" to (R.string.settings_search_android_root to R.string.settings_search_android_root_path),
    )
    fun title(context: Context, id: String): String? = resources[id]?.let { context.getString(it.first) }
    fun localize(context: Context, entries: List<SettingsEntry>) = entries.map { entry ->
        resources[entry.id]?.let { pair -> entry.copy(title = context.getString(pair.first),
            breadcrumb = context.getString(pair.second), aliases = entry.aliases + entry.title) } ?: entry
    }
}
